plugins {
	alias libs.plugins.architectury.loom apply false
	alias libs.plugins.preprocessor
	alias libs.plugins.lombok
}

preprocess {
	strictExtraMappings = false

	var mc12108 = createNode("1.21.8", 1_21_08, 'mojang')
	var mc12101 = createNode("1.21.1", 1_21_01, 'mojang')

	mc12108.link(mc12101, file("versions/mappings-1.21.8-to-1.21.1.txt"))

	for (final def node in getNodes()) {
		findProject(node.project).ext.mcVersion = node.mcVersion
	}
}

ext {
	Map env = System.getenv()

	getEnv = {
		return env
	}

	getOrDefault = { String key, String defaultValue ->
		String value
		(value = project.findProperty(key)) && !value.isEmpty() ? value : defaultValue
	}

	getVersionSuffix = {
		String number = env.GITHUB_RUN_NUMBER ? env.GITHUB_RUN_NUMBER : 'x'
		String type = env.VERSION_TYPE
		switch (type) {
			case 'release': return ''
			case 'beta': return "+snapshot.${number}"
			case 'alpha': return "+pr.${number}"
			default: return "+build.${number}"
		}
	}

	getModVersion = { Project proj ->
		return "${proj.property("mod.version")}${getVersionSuffix()}"
	}
}

tasks.register("cleanPreprocessSources") {
	it.group = "${project.property("mod.id")}"

	doFirst {
		subprojects {
			def path = project.projectDir.toPath().resolve("build/preprocessed")
			path.toFile().deleteDir()
		}
	}
}

tasks.register("copyAllJars", Copy) {
	var libs = it.rootSpec.addChild()
	var devlibs = it.rootSpec.addChild()
	subprojects.forEach { subproject ->
		libs.from(subproject.layout.buildDirectory.dir("libs")) {
			include("*.jar")
		}
		devlibs.from(subproject.layout.buildDirectory.dir("devlibs")) {
			include("*.jar")
		}
	}
	doFirst {
		delete layout.buildDirectory.dir("libs")
		delete layout.buildDirectory.dir("devlibs")
	}
	into(layout.buildDirectory)
	libs.into("libs")
	devlibs.into("devlibs")
	it.with(libs, devlibs)
	duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
