# Gradle properties
org.gradle.jvmargs=-Xmx2G

# Mod Properties
mod.archives_base_name=qca
mod.artifact_name=qca
mod.description=An addition for carpet.
mod.homepage=https://qiushui1012.com/
mod.id=qca
mod.license=Apache License 2.0
mod.maven_group=com.qiushui1012.mod
mod.name=Qualia Carpet Addition
mod.sources=https://github.com/QiuShui1012/Qualia-Carpet-Addition
mod.version=2.1.0
