modLoader="javafml"
loaderVersion="${loader_version_range}"
license="Apache License 2.0"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Qualia Carpet Addition"
displayURL = "https://qiushui1012.github.io/"
issueTrackerURL = "https://github.com/QiuShui1012/Qualia-Carpet-Addition/issues"
logoFile = "pack.png"
authors = "QiuShui1012"

description = '''
An addition for carpet.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="bedsheet"
    mandatory=true
    versionRange="[0.2.1,)"
    ordering="NONE"
    side="BOTH"

