# Dependency Versions
dependencies.minecraft_dependency=>=26.1 <26.2
dependencies.minecraft_version=26.1.2
dependencies.neoforge_version=26.1.2.95
dependencies.rolling_gate_version=1.1.0+build.69
loom.platform=neoforge

action.minecraft_version=26.1.2
action.neoforge_version=26.1.2.95
action.java_version=25
