[versions]

# Enviroment Properties
minecraft = "1.21.1"
neoforge = "21.1.180"

parchment = "1.21.1,2024.11.17"

# Dependency Properties
rollinggate = "1.1.0+build.55"

# Gradle Plugin Properties
mdg = "2.0.95"
lombok = "8.7.1"
modpublish = "0.8.4"

[libraries]

# NeoForge
rollinggate = { group = "dev.anvilcraft.rg", name = "RollingGate", version.ref = "rollinggate" }

[plugins]

mdg = { id = "net.neoforged.moddev", version.ref = "mdg" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
modpublish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "modpublish"}
