# Dependency Versions
dependencies.minecraft_dependency=>=1.21.10 <26.1
dependencies.minecraft_version=1.21.10
dependencies.neoforge_version=21.10.64
dependencies.rolling_gate_version=1.1.0+build.68
loom.platform=neoforge

action.minecraft_version=1.21.10
action.neoforge_version=21.10.64
action.java_version=21
