# Dependency Versions
dependencies.minecraft_dependency=>=1.21.8 <1.21.10
dependencies.minecraft_version=1.21.8
dependencies.neoforge_version=21.8.54
dependencies.rolling_gate_version=1.1.0+build.67
loom.platform=neoforge

action.minecraft_version=1.21.8
action.loader_version=21.8.54
action.java_version=21
