name: Build and Test
on:
  workflow_call:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
      version_type:
        description: 'Version Type'
        required: true
        type: string
      mod_id:
        description: 'Mod ID'
        required: true
        type: string
      mod_name:
        description: 'Mod Name'
        required: true
        type: string
      ci_build:
        description: 'CI Build'
        required: true
        type: boolean
      pr_build:
        description: 'PR Build'
        required: true
        type: boolean
      gametest:
        description: 'Should GameTest'
        required: false
        type: boolean
        default: false
      publish:
        description: 'Should publish'
        required: false
        type: boolean
        default: false

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      NOT_DEV: true
      CI_BUILD: ${{ inputs.ci_build }}
      PR_BUILD: ${{ inputs.pr_build }}
      VERSION_TYPE: ${{ inputs.version_type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java 25
        uses: actions/setup-java@v5.2.0
        with:
          distribution: zulu
          java-version: 25

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build Subproject
        run: ./gradlew :${{ inputs.version }}:build

      - name: Read Properties
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: versions/${{ inputs.version }}/gradle.properties
          properties: 'dependencies.minecraft_dependency dependencies.carpet_version dependencies.fabric_api_version actions.minecraft_version actions.java_version'

      - name: Get Version
        id: version
        run: |
          MESSAGE=$(ls ./versions/${{ inputs.version }}/build/libs/* | grep sources.jar -v | awk -F '${{ inputs.mod_id }}-fabric-|.jar' '{print $2}')
          echo "version=$MESSAGE" >> $GITHUB_OUTPUT
      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "${{ inputs.mod_name }} ${{ steps.version.outputs.version }}"
          path: versions/${{ inputs.version }}/build/libs/${{ inputs.mod_id }}-fabric-${{ steps.version.outputs.version }}.jar

      - name: Setup Java ${{ steps.properties.outputs.actions-java_version }} For Game Test
        if: ${{ inputs.gametest }}
        uses: actions/setup-java@v5.2.0
        with:
          distribution: zulu
          java-version: ${{ steps.properties.outputs.actions-java_version }}

      - name: Game Test
        if: ${{ inputs.gametest }}
        uses: Anvil-Dev/dedicated-server-launch-test@universal
        with:
          minecraft_version: '${{ steps.properties.outputs.actions-minecraft_version }}'
          mod_loader: 'fabric'
          loader_version: '0.18.4'
          mods: versions/${{ inputs.version }}/build/libs/${{ inputs.mod_id }}-fabric-${{ steps.version.outputs.version }}.jar
          maven-repos: |
            https://maven.fabricmc.net/
            https://masa.dy.fi/maven/
          maven-mods: |
            net.fabricmc.fabric-api:fabric-api:${{ steps.properties.outputs.dependencies-fabric_api_version }}
            carpet:fabric-carpet:${{ steps.properties.outputs.dependencies-carpet_version }}
          quiet-setup: True

      - name: Upload Release Jar
        if: ${{ !inputs.ci_build && !inputs.pr_build }}
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            versions/${{ inputs.version }}/build/libs/${{ inputs.mod_id }}-fabric-${{ steps.version.outputs.version }}.jar

      - name: Publish Mod
        if: ${{ inputs.publish }}
        uses: Kir-Antipov/mc-publish@v3.3
        continue-on-error: true
        with:
          name: "${{ inputs.mod_name }} For Fabric v${{ steps.version.outputs.version }}"
          version: ${{ steps.version.outputs.version }}
          loaders: fabric
          game-versions: ${{ steps.properties.outputs.dependencies-minecraft_dependency }}
          version-type: ${{ env.VERSION_TYPE }}
          fail-mode: skip

          dependencies: |
            fabric-api@${{ steps.properties.outputs.dependencies-fabric_api_version }}(required){modrinth:P7dR8mSH}{curseforge:306612}
            carpet@${{ steps.properties.outputs.dependencies-carpet_version }}(required){modrinth:TQTTVgYE}{curseforge:349239}

          modrinth-id: JyI4tI00
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true

          curseforge-id: 1166675
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            versions/${{ inputs.version }}/build/libs/${{ inputs.mod_id }}-fabric-${{ steps.version.outputs.version }}.jar
            versions/${{ inputs.version }}/build/libs/${{ inputs.mod_id }}-fabric-${{ steps.version.outputs.version }}-sources.jar
