name: CI for QCA
on:
  workflow_dispatch:
  push:
    branches:
      - release/**
      - dev/**
    paths:
      - .github/workflows/ci.yml
      - .github/workflows/setup.yml
      - .github/workflows/build_and_upload.yml
      - .github/workflows/test_and_publish.yml
      - gradle/**
      - src/**
      - versions/*/src/**
      - versions/*/gradle.properties
      - versions/*-map2-*
      - versions/build.gradle
      - build.gradle
      - gradle.properties
      - settings.gradle
      - settings.json

jobs:
  setup:
    name: Setup Environment
    uses: ./.github/workflows/setup.yml

  build:
    name: Build and Upload
    needs: setup
    permissions:
      contents: write
    uses: ./.github/workflows/build_and_upload.yml
    with:
      mod_id: "${{ needs.setup.outputs.mod_id }}"
      mod_name: "${{ needs.setup.outputs.mod_name }}"
      versions: "${{ needs.setup.outputs.versions }}"
      ci_build: true

  test:
    name: Test and Publish
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/test_and_publish.yml
    with:
      mod_id: "${{ needs.build.outputs.mod_id }}"
      mod_name: "${{ needs.build.outputs.mod_name }}"
      versions: "${{ needs.build.outputs.versions }}"
      version_type: 'alpha'
      build_type: 'snapshot'
      ci_build: true
    secrets:
      curseforge_token: ${{ secrets.CURSEFORGE_TOKEN }}
      modrinth_token: ${{ secrets.MODRINTH_TOKEN }}
