name: Pull Request Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - release/**
      - dev/**
    paths:
      - .github/workflows/pull_request.yml
      - .github/workflows/setup.yml
      - .github/workflows/build_and_upload.yml
      - .github/workflows/test_and_publish.yml
      - gradle/**
      - src/**
      - versions/*/src/**
      - versions/*/gradle.properties
      - versions/*-map2-*
      - versions/build.gradle
      - build.gradle
      - gradle.properties
      - settings.gradle
      - settings.json

permissions:
  contents: read
  actions: read
  packages: read
  pull-requests: write

jobs:
  setup:
    name: Setup Environment
    uses: ./.github/workflows/setup.yml

  build:
    name: Build and Upload
    needs: setup
    permissions:
      contents: write
    uses: ./.github/workflows/build_and_upload.yml
    with:
      mod_id: "${{ needs.setup.outputs.mod_id }}"
      mod_name: "${{ needs.setup.outputs.mod_name }}"
      versions: "${{ needs.setup.outputs.versions }}"
      pr_build: true

  test:
    name: Test and Publish
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/test_and_publish.yml
    with:
      mod_id: "${{ needs.build.outputs.mod_id }}"
      mod_name: "${{ needs.build.outputs.mod_name }}"
      versions: "${{ needs.build.outputs.versions }}"
      build_type: 'pr'
      pr_build: true
