name: Upload Release Assets
on:
  release:
    types:
      - published
    branches:
      - release/**
      - dev/**

jobs:
  setup:
    name: Setup Environment
    uses: ./.github/workflows/setup.yml

  build:
    name: Build and Upload
    needs: setup
    permissions:
      contents: write
    uses: ./.github/workflows/build_and_upload.yml
    with:
      mod_id: "${{ needs.setup.outputs.mod_id }}"
      mod_name: "${{ needs.setup.outputs.mod_name }}"
      versions: "${{ needs.setup.outputs.versions }}"

  test:
    name: Test and Publish
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/test_and_publish.yml
    with:
      mod_id: "${{ needs.build.outputs.mod_id }}"
      mod_name: "${{ needs.build.outputs.mod_name }}"
      versions: "${{ needs.build.outputs.versions }}"
      version_type: ${{ github.event.release.prerelease && 'beta' || 'release' }}
      build_type: 'release'
      gametest: false
    secrets:
      curseforge_token: ${{ secrets.CURSEFORGE_TOKEN }}
      modrinth_token: ${{ secrets.MODRINTH_TOKEN }}
