name: test_and_publish.yml
on:
  workflow_call:
    inputs:
      mod_id:
        type: string
        required: true
      mod_name:
        type: string
        required: true
      versions:
        description: 'Versions'
        type: string
        required: true
      version_type:
        description: 'Version Type'
        type: string
      build_type:
        description: 'Build Type'
        type: string
        required: true
      ci_build:
        description: 'CI Build'
        type: boolean
        default: false
      pr_build:
        description: 'PR Build'
        type: boolean
        default: false
      gametest:
        description: 'Should GameTest'
        type: boolean
        default: true
    secrets:
      curseforge_token:
        description: 'Curseforge Token'
        required: false
      modrinth_token:
        description: 'Modrinth Token'
        required: false

jobs:
  tap:
    name: Test and Publish Version ${{ matrix.version }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(inputs.versions).versions }}
    env:
      NOT_DEV: true
      CI_BUILD: ${{ inputs.ci_build }}
      PR_BUILD: ${{ inputs.pr_build }}
      BUILD_TYPE: ${{ inputs.build_type }}
      VERSION_TYPE: ${{ inputs.version_type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download Jar
        uses: actions/download-artifact@v8
        with:
          name: "${{ inputs.mod_name }} ${{ matrix.version }} Jar"
          path: versions/${{ matrix.version }}/build/libs/

      - name: Get Version
        id: version
        run: |
          MESSAGE=$(ls ./versions/${{ matrix.version }}/build/libs/* | grep sources.jar -v | awk -F '${{ inputs.mod_id }}-neo-rg-${{ matrix.version }}-|.jar' '{print $2}')
          echo "version=$MESSAGE" >> $GITHUB_OUTPUT

      - name: Read Properties
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: versions/${{ matrix.version }}/gradle.properties
          properties: 'dependencies.minecraft_dependency dependencies.rolling_gate_version action.minecraft_version action.loader_version action.java_version action.extra_mods'

      - name: Setup Java ${{ steps.properties.outputs.action-java_version }}
        uses: actions/setup-java@v5.5.0
        with:
          distribution: zulu
          java-version: ${{ steps.properties.outputs.action-java_version }}

      - name: Game Test
        uses: Anvil-Dev/dedicated-server-launch-test@universal
        if: ${{ inputs.gametest }}
        with:
          minecraft_version: '${{ steps.properties.outputs.action-minecraft_version }}'
          mod_loader: neoforge
          loader_version: '${{ steps.properties.outputs.action-loader_version }}'
          mods: versions/${{ matrix.version }}/build/libs/${{ inputs.mod_id }}-neo-rg-${{ matrix.version }}-${{ steps.version.outputs.version }}.jar
          maven-repos: |
            https://server.cjsah.net:1002/maven/
          maven-mods: |
            dev.anvilcraft.rg:RollingGate:${{ steps.properties.outputs.dependencies-rolling_gate_version }}
          quiet-setup: True

      - name: Upload Release Jar
        uses: softprops/action-gh-release@v0.1.15
        if: ${{ !inputs.ci_build && !inputs.pr_build }}
        with:
          files: |
            versions/${{ matrix.version }}/build/libs/${{ inputs.mod_id }}-neo-rg-${{ matrix.version }}-${{ steps.version.outputs.version }}.jar

      - name: Download Sources Jar
        uses: actions/download-artifact@v8
        with:
          name: "${{ inputs.mod_name }} ${{ matrix.version }} Sources Jar"
          path: versions/${{ matrix.version }}/build/libs/

      - name: Publish Mod
        uses: Kira-NT/mc-publish@v3.3
        if: ${{ !inputs.pr_build }}
        with:
          name: "${{ inputs.mod_name }} ${{ matrix.version }} v${{ steps.version.outputs.version }}"
          version: ${{ steps.version.outputs.version }}
          loaders: ${{ steps.properties.outputs.action-mod_loader }}
          game-versions: ${{ steps.properties.outputs.dependencies-minecraft_dependency }}
          version-type: ${{ env.VERSION_TYPE }}

          dependencies: |
            rolling_gate@${{ steps.properties.outputs.dependencies-rolling_gate_version }}(required){modrinth:HXsmHiKu}{curseforge:1194894}

          modrinth-id: 'JyI4tI00'
          modrinth-token: ${{ secrets.modrinth_token }}
          modrinth-featured: true

          curseforge-id: '1166675'
          curseforge-token: ${{ secrets.curseforge_token }}

          files: |
            versions/${{ matrix.version }}/build/libs/${{ inputs.mod_id }}-neo-rg-${{ matrix.version }}-${{ steps.version.outputs.version }}.jar
            versions/${{ matrix.version }}/build/libs/${{ inputs.mod_id }}-neo-rg-${{ matrix.version }}-${{ steps.version.outputs.version }}-sources.jar
